Repository car12lin12/InstaBaddies, pull requests merged in 2020-03, with the labels that each got.

#49 Add and delete a post
  lib/client/src/components/CreatePost.js
  lib/client/src/components/DeletePost.js
  lib/client/src/components/Header.js
  lib/client/src/components/Home.js
  lib/client/src/components/Login.js
  lib/client/src/components/Navbar.js
  lib/client/src/components/Post.js
  lib/client/src/components/Profile.js
  lib/client/src/components/Signup.js
  lib/client/src/redux/actions/dataActions.js
  lib/client/src/redux/actions/userActions.js
  lib/client/src/redux/reducers/dataReducer.js
  lib/client/src/redux/reducers/userReducer.js
Labels: 8, :bookmark: Task, Front-end, L3

#52 Added a like button with an icon.
  lib/client/src/components/Post.js
Labels: :bookmark: Task, Front-end

#50 Submit Comments
  lib/client/public/manifest.json
  lib/client/src/App.js
  lib/client/src/components/layout/Navbar.js
  lib/client/src/components/posts/CommentForm.js
  lib/client/src/components/posts/Comments.js
  lib/client/src/components/posts/CreatePost.js
  lib/client/src/components/posts/DeletePost.js
  lib/client/src/components/posts/Post.js
  lib/client/src/components/posts/PostDialog.js
  lib/client/src/components/profile/EditDetails.js
  lib/client/src/components/profile/Profile.js
  lib/client/src/components/profile/StaticProfile.js
  lib/client/src/pages/home.js
  lib/client/src/pages/user.js
  lib/client/src/redux/actions/dataActions.js
  lib/client/src/redux/reducers/dataReducer.js
  lib/client/src/redux/reducers/uiReducer.js
  lib/client/src/util/AuthRoute.js
  lib/instabadd-functions/functions/handlers/posts.js
Labels: 5, :bookmark: Task, Front-end, L3

#60 Notifications
  .travis.yml
  lib/client/src/App.js
  lib/client/src/components/layout/Navbar.js
  lib/client/src/components/layout/Notifications.js
  lib/client/src/components/posts/Post.js
  lib/client/src/components/posts/PostDialog.js
  lib/client/src/components/profile/Profile.js
  lib/client/src/images/no-img.png
  lib/client/src/pages/home.js
  lib/client/src/pages/user.js
  lib/client/src/redux/actions/dataActions.js
  lib/client/src/redux/actions/userActions.js
  lib/client/src/redux/reducers/userReducer.js
  lib/client/src/redux/types.js
  lib/client/src/util/PostSkeleton.js
  lib/client/src/util/ProfileSkeleton.js
  lib/client/src/util/history.js
  lib/instabadd-functions/functions/index.js
  lib/instabadd-functions/functions/package.json
Labels: :bookmark: Task, Front-end, L3

#61 Follow and unfollow
  lib/client/src/App.js
  lib/client/src/components/layout/Navbar.js
  lib/client/src/components/posts/Post.js
  lib/client/src/components/profile/EditDetails.js
  lib/client/src/components/profile/Profile.js
  lib/client/src/components/profile/StaticProfile.js
  lib/client/src/pages/home.js
  lib/client/src/pages/user.js
  lib/instabadd-functions/README.md
  lib/instabadd-functions/functions/index.js
Labels: 8, Front-end, L3

#64 Search bar and delete comment
  README.md
  lib/client/package-lock.json
  lib/client/package.json
  lib/client/src/components/layout/Navbar.js
  lib/client/src/components/posts/CommentForm.js
  lib/client/src/components/posts/Comments.js
  lib/client/src/components/posts/DeleteComment.js
  lib/client/src/components/posts/Post.js
  lib/client/src/components/posts/PostDialog.js
  lib/client/src/components/profile/StaticProfile.js
  lib/client/src/redux/actions/dataActions.js
  lib/client/src/redux/reducers/dataReducer.js
  lib/client/src/redux/types.js
  lib/instabadd-functions/functions/handlers/posts.js
  lib/instabadd-functions/functions/index.js
Labels: 21, :book: Epic, Back-end, Front-end, L3

#69 Unit tests and static analysis tool
  .travis.yml
  README.md
  lib/client/.eslintrc.json
  lib/client/package-lock.json
  lib/client/package.json
  lib/client/src/index.js
  lib/instabadd-functions/functions/.eslintrc.json
  lib/instabadd-functions/functions/handlers/posts.js
  lib/instabadd-functions/functions/handlers/users.js
  lib/instabadd-functions/functions/index.js
  lib/instabadd-functions/functions/package-lock.json
  lib/instabadd-functions/functions/package.json
  lib/instabadd-functions/functions/test/addUserDetails.test.js
  lib/instabadd-functions/functions/test/commentOnPost.test.js
  lib/instabadd-functions/functions/test/createPost.test.js
  lib/instabadd-functions/functions/test/deleteComment.js
  lib/instabadd-functions/functions/test/deletePost.test.js
  lib/instabadd-functions/functions/test/followerUser.test.js
  lib/instabadd-functions/functions/test/getPost.test.js
  lib/instabadd-functions/functions/test/getUserDetails.test.js
  lib/instabadd-functions/functions/test/randyFreche.jpg
  lib/instabadd-functions/functions/test/service-account-key.json
  lib/instabadd-functions/functions/test/unfollowUser.test.js
  lib/instabadd-functions/functions/test/uploadImage.test.js
  lib/instabadd-functions/functions/util/fbAuth.js
  lib/instabadd-functions/functions/util/validators.js
  package.json
Labels: 34, Back-end, CI :factory:, L3
